---
- name: 修改selinux配置文件
  lineinfile:
    dest: /etc/selinux/config
    state: present
    regexp: 'SELINUX='
    line: 'SELINUX=disabled'
  when:
    - ansible_selinux['status'] != 'disabled'
   
- name: 确认当前selinux状态
  command: getenforce
  register: selinux_stat

- name: 关闭selinux
  command: setenforce 0
  when:
    - selinux_stat.stdout != 'Disabled'
