---
- name: 配置yum源
  template:
    src: prometheus.repo.j2
    dest: /etc/yum.repos.d/prometheus
  when:
    - mirrors is defined

- name: 安装prometheus
  yum:
    name: "{{ item }}"
    state: absent
    enablerepo: prometheus
  with_items:
    - prometheus
    - node_exporter
    - grafana-server

- name: 修改配置文件
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Restart Prometheus
